<?php
	class LabelHelper {
		public static function getLabel($field) {
			$field =  strtolower($field);
			$labels = array(
				'submit' => 'Simpan',
				'manage_block' => 'Block',
				'block' => 'Block',
				'create_block' => 'Tambah Block',
				'edit_block' => 'Edit Block',
				'manage_brand' => 'Merk',
				'create_brand' => 'Tambah Merk',
				'edit_brand' => 'Edit Merk',
				'manage_category' => 'Kategori',
				'create_category' => 'Tambah Kategori',
				'edit_category' => 'Edit Kategori',
				'manage_agent' => 'Agen',
				'create_agent' => 'Tambah Agen',
				'edit_agent' => 'Edit Agen',
				'agent' => 'Agen',
				'manage_customer' => 'Customer',
				'create_customer' => 'Tambah Customer',
				'edit_customer' => 'Edit Customer',
				'customer' => 'Customer',
				'personal_info' => 'Data Pribadi',
				'shipping_address' => 'Alamat Pengiriman',
				'billing_address' => 'Alamat Tagihan',
				'manage_order' => 'Order',
				'order' => 'Order',
				'phone' => 'No. Telp',
				'mobile_phone' => 'No. HP',
				'product' => 'Produk',
				'sku' => 'SKU',
				'price' => 'Harga',
				'qty' => 'QTY',
				'discount' => 'Diskon',
				'subtotal' => 'Subtotal',
				'manage_page' => 'Halaman',
				'create_page' => 'Tambah Halaman',
				'edit_page' => 'Edit Halaman',
				'page' => 'Halaman',
				'manage_product' => 'Produk',
				'create_product' => 'Tambah Produk',
				'edit_product' => 'Edit Produk',
				'dashboard' => 'Dashboard',
				'categories' => 'Kategori',
				'images' => 'Gambar',
				'upload' => 'Upload',
				'product_info' => 'Info Produk',
				'product_categories' => 'Produk Kategori',
				'upload_product_images' => 'Upload Gambar Produk',
				'manage_user' => 'User',
				'create_user' => 'Tambah User',
				'edit_user' => 'Edit User',
				'user' => 'User',
				'login' => 'Log In',
				'manage_homeslider' => 'Slider',
				'create_homeslider' => 'Tambah Slider',
				'edit_homeslider' => 'Edit Slider',
				'homeslider' => 'Slider',
				'manage_document' => 'Dokumen',
				'create_document' => 'Tambah Dokumen',
				'edit_document' => 'Edit Dokumen',
				'manage_featured_brand' => 'Merk Unggulan',
				'create_featured_brand' => 'Tambah Merk',
				'edit_featured_brand' => 'Edit Merk',
				'sort_category' => 'Urutan Kategori',
				'setting' => 'Pengaturan',
				'edit_setting' => 'Ubah Pengaturan',
				'manage_storelocation' => 'Lokasi Toko',
				'create_storelocation' => 'Tambah Lokasi Toko',
				'edit_storelocation' => 'Edit Lokasi Toko',
				// 'homeslider' => 'Lokasi Toko',
				'manage_video' => 'Video',
				'video' => 'Video',
				'create_video' => 'Tambah Video',
				'edit_video' => 'Edit Video',
				'manage_uom' => 'Master Satuan',
				'uom' => 'Satuan',
				'create_uom' => 'Tambah Satuan',
				'edit_uom' => 'Edit Satuan',
			);

			return isset($labels[$field]) ? $labels[$field] : ucwords($field);
		}
	}